FROM repbioinfo/xenome.2017.01:xenome-1.0.0


#RUN apt-get update && \
#    apt-get upgrade -y && \
#    apt-get install -y \
#        libhdf5-dev \
#        libcurl4-gnutls-dev \
#        libssl-dev \
#        libxml2-dev \
#        libpng-dev \
#        libxt-dev \
#        zlib1g-dev \
#        libbz2-dev \
#        liblzma-dev \
#        libglpk40 \
#        ffmpeg \
#        libcairo2-dev \
#        libglu1-mesa-dev \
#        libgsl-dev \
#        libmagick++-dev \
#g++ libboost-all-dev pandoc \
#	zlib1g-dev libbz2-dev libsqlite3-dev \
#        libmariadb-dev \
#        libssh2-1-dev \
#        libudunits2-dev cmake git\
#        software-properties-common && \
#    apt-get clean all && \
#    apt-get purge && \
#    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
#RUN apt-get update
#RUN apt-get install vim -y
#RUN git clone https://github.com/data61/gossamer
# RUN cd gossamer && mkdir build && cmake .. && make && make test && make install

